#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           TEST,          tmotorVex393_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           TEST2,         tmotorVex393_MC29, openLoop, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "Amp_Limiter_Func.c"




SmartMotor motorA;
SmartMotor motorB;


task input();


task main()
{


init_SmartMotor(motorA, TEST);
init_SmartMotor(motorB, TEST2);


clearTimer(T1);
startTask(input);

while(1){

state_SmartMotor(motorA);

clearDebugStream();
writeDebugStream("Effort:%d\n",motorA.effort);
writeDebugStream("Effort Delta:%d\n",motorA.deltaEffort);
writeDebugStream("Check1:%d\n",motor[TEST]);
writeDebugStream("BackEMF:%d\n",motorA.backEMF);
writeDebugStream("Target Amp:%f\n",motorA.targetAmp);
writeDebugStream("Amp:%f\n",motorA.amps);
writeDebugStream("Amp/s:%f\n",motorA.ampsPsec);
writeDebugStream("Current Volts/s:%f\n",motorA.currentVolts);
writeDebugStream("Effort Volts/s:%f\n",motorA.effortVolts);
writeDebugStream("sec:%d\n",time1[T1]/1000);
writeDebugStream("RPM:%d\n",getMotorVelocity(TEST));
writeDebugStream("Start Volts:%d\n",motorA.startVolts);

state_SmartMotor(motorB);

writeDebugStream("\n\nEffort:%d\n",motorB.effort);
writeDebugStream("Effort Delta:%d\n",motorB.deltaEffort);
writeDebugStream("Check1:%d\n",motor[TEST2]);
writeDebugStream("BackEMF:%d\n",motorB.backEMF);
writeDebugStream("Target Amp:%f\n",motorB.targetAmp);
writeDebugStream("Amp:%f\n",motorB.amps);
writeDebugStream("Amp/s:%f\n",motorB.ampsPsec);
writeDebugStream("Current Volts/s:%f\n",motorB.currentVolts);
writeDebugStream("Delta Volts/s:%f\n",motorB.voltDelta);
writeDebugStream("sec:%d\n",time1[T1]/1000);
writeDebugStream("RPM:%d\n",getMotorVelocity(TEST2));
writeDebugStream("Off:%d\n",motorB.off);


wait1Msec(100);

}
}

task input()
{

while(1){

/*
if(vexRT[Btn8D])
targetVelocity = 5 + targetVelocity;

else if(vexRT[Btn8U])
targetVelocity = targetVelocity - 5;
*/

if(vexRT[Btn8L])
motorA.off = true;

else if(vexRT[Btn8R])
motorA.off = false;

motor[TEST] = motorA.effort;
motor[TEST2] = -motorB.effort;

/*
totalAmp = amps + totalAmp;
++timeDiv;

ampsPsec = totalAmp/timeDiv;
currentVolts = startVolts - voltDelta;
*/

wait1Msec(200);

}



}
