#pragma config(Motor,  port1,           IntakeR,       tmotorVex393_HBridge, openLoop)
#pragma config(Motor,  port2,           BR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           FR,            tmotorVex393HighSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port4,           FL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           RTB,           tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port7,           RM,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           LM,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           LTB,           tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port10,          IntakeL,       tmotorVex393_HBridge, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		motor[FL] = vexRT[Ch3] + vexRT[Ch4];
		motor[FR] = vexRT[Ch3] - vexRT[Ch4];

		motor[BL] = vexRT[Ch3] + vexRT[Ch4];
		motor[BR] = vexRT[Ch3] - vexRT[Ch4];

		int tower_effort = 60;

		if (vexRT[Btn5U])
		{
		 	motor[RTB] = tower_effort;
		 	motor[LTB] = tower_effort;
		 	motor[RM]  = tower_effort;
		 	motor[LM]  = tower_effort;

		}
		else if (vexRT[Btn5D])
		{
			motor[RTB] = -tower_effort;
		 	motor[LTB] = -tower_effort;
		 	motor[RM]  = -tower_effort;
		 	motor[LM]  = -tower_effort;
		}
		else
		{
			motor[RTB] = 0;
		 	motor[LTB] = 0;
		 	motor[RM]  = 0;
		 	motor[LM]  = 0;
		}

		if (vexRT[Btn6U]) //Turn intake wheels to suck stuff in
		{
			motor[IntakeL] = 60;
			motor[IntakeR] = 60;
		}
		else if (vexRT[Btn6D])
		{
			motor[IntakeL] = -60;
			motor[IntakeR] = -60;
		}
		else
		{
			motor[IntakeL] = 0;
			motor[IntakeR] = 0;
		}
	}







}
