#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, in1,    BATTERY,        sensorAnalog)
#pragma config(Sensor, dgtl1,  BUTTON,         sensorDigitalIn)
#pragma config(Sensor, dgtl2,  LIMITSWITCH,    sensorDigitalIn)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_5,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_6,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           BL,            tmotorVex393_MC29, openLoop, encoderPort, I2C_4)
#pragma config(Motor,  port3,           BR,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_1)
#pragma config(Motor,  port4,           FL,            tmotorVex393_MC29, openLoop, encoderPort, I2C_3)
#pragma config(Motor,  port5,           FR,            tmotorVex393_MC29, openLoop, reversed, encoderPort, I2C_2)
#pragma config(Motor,  port6,           ARM,           tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, I2C_5)
#pragma config(Motor,  port7,           ARMSLAVE,      tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port8,           ARMSLAVE2,     tmotorVex393TurboSpeed_MC29, openLoop, reversed)
#pragma config(Motor,  port9,           CLAW,          tmotorVex393_MC29, openLoop, encoderPort, I2C_6)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#pragma platform(VEX2)
#pragma competitionControl(Competition)

#include "utility.c"
#include "competition.c"
