#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  FR,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  FL,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_3,  BL,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_4,  BR,             sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           FR,            tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight, encoderPort, I2C_1)
#pragma config(Motor,  port3,           FL,            tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_2)
#pragma config(Motor,  port8,           BL,            tmotorVex393HighSpeed_MC29, openLoop, driveLeft, encoderPort, I2C_3)
#pragma config(Motor,  port9,           BR,            tmotorVex393HighSpeed_MC29, openLoop, reversed, driveRight, encoderPort, I2C_4)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#include "SmartMotor.c"

task _FL
{
	start_SmartMotor(smart_motor[FL]);
}

task _BL
{
	start_SmartMotor(smart_motor[BL]);
}

task _FR
{
	start_SmartMotor(smart_motor[FR]);
}

task _BR
{
	start_SmartMotor(smart_motor[BR]);
}

task main ()
{
	init_SmartMotor(smart_motor[FL], FL);
	init_SmartMotor(smart_motor[BL], BL);
	init_SmartMotor(smart_motor[FR], FR);
	init_SmartMotor(smart_motor[BR], BR);

	startTask(_FL);
	startTask(_BL);
	startTask(_FR);
	startTask(_BR);

	group_SmartMotor(0,smart_motor[FL]);
	group_SmartMotor(0,smart_motor[BL]);
	group_SmartMotor(0,smart_motor[FR]);
	group_SmartMotor(0,smart_motor[BR]);

	monitorGroup[0] = true;

	for (;;)
	{
		int left_effort = (vexRT[Ch3] + vexRT[Ch1]);
		int right_effort = (vexRT[Ch3] - vexRT[Ch1]);

		/*
		motor[FL] = left_effort;
		motor[BL] = left_effort;
		motor[FR] = right_effort;
		motor[BR] = right_effort;*/

		smart_motor[FL].input = left_effort * groupMultiplier[0];
		smart_motor[BL].input = left_effort * groupMultiplier[0];
		smart_motor[FR].input = right_effort * groupMultiplier[0];
		smart_motor[BR].input = right_effort * groupMultiplier[0];

		clearDebugStream();
		// writeDebugStream("Group Mult: %f\n", groupMultiplier[0]);
		writeDebugStream("Amps: %f\n", groupAmps[0]);
		writeDebugStream("Amp Delta: %f\n", groupDelta[0]);
		writeDebugStream("Amp Limit: %f\n", groupAmpsLimit[0]);

		wait1Msec(10);
	}
}
