#pragma config(Motor,  port2,           LD,            tmotorVex393_MC29, openLoop, reversed)
#pragma config(Motor,  port3,           RD,            tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port5,           ARM1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port6,           ARM2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ARM3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           CLAW1,         tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           CLAW2,         tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	while (true)
	{
		int left_control = vexRT[Ch2];
		int right_control = vexRT[Ch3];

		motor[LD] = left_control;
		motor[RD] = right_control;

		int effort = 100;

		if (vexRT[Btn5U])
		{
			motor[ARM1] = effort;
			motor[ARM2] = effort;
			motor[ARM3] = effort;
		}
		else if (vexRT[Btn5D])
		{
			motor[ARM1] = -effort;
			motor[ARM2] = -effort;
			motor[ARM3] = -effort;
		}
		else
		{
			motor[ARM1] = 0;
			motor[ARM2] = 0;
			motor[ARM3] = 0;
		}

		if (vexRT[Btn6U])
		{
			motor[CLAW1] = effort;
			motor[CLAW2] = effort;
		}
		else if (vexRT[Btn6D])
		{
			motor[CLAW1] = -effort;
			motor[CLAW2] = -effort;
		}
		else
		{
			motor[CLAW1] = 0;
			motor[CLAW2] = 0;
		}
	}
}
