#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  ,               sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           LIFT,          tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, I2C_1)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

#define NUMBER_OF_MOTORS 5
#define MAX_BUFFER_SIZE 128

char buffer[MAX_BUFFER_SIZE];

float _motor[NUMBER_OF_MOTORS];
int _encoder[NUMBER_OF_MOTORS];

void applySoftStart()
{
	for (int i = 0; i < NUMBER_OF_MOTORS; i++)
	{
		float target = _motor[i];
		int current = motor[i];

		float delta = 1000; // How much it effort it changes per second

		delta = delta/100;

		// If the target and current value are further away than delta.
		if (abs(target - current) > delta)
		{
			if (target > current)
			{
				motor[i] += delta;
			}
			else
			{
				motor[i] -= delta;
			}
		}
		else
		{
			motor[i] = target;
		}
	}
}

task main()
{
	// Set soft motor array and custom encoder array to zero.
	for (int i = 0; i < NUMBER_OF_MOTORS; i++)
	{
		_motor[i] = 0;
		_encoder[i] = 0;

		nMotorEncoder[i] = 0;
	}
	clearDebugStream();

	sprintf(buffer, "Size of motor array: %d\n", sizeof(motor)/4);
	writeDebugStream(buffer);

	datalogClear();

	bool kill_timer = false;

	while (true)
	{
		if (kill_timer)
		{
			kill_timer = false;
		}
		else
		{
			kill_timer = true;
		}

		word instantaneous = vexRT[Btn5U];
		word kill = vexRT[Btn5D];

		float volt = nImmediateBatteryLevel;

		clearDebugStream();
		sprintf(buffer, "Voltage: %d\n", nImmediateBatteryLevel);
		writeDebugStream(buffer);

		if (!instantaneous)
		{
			if (vexRT[Btn6U])
			{
				_motor[LIFT] = 128;
			}
			else if (vexRT[Btn6D])
			{
				_motor[LIFT] = -128;
			}
			else
			{
				_motor[LIFT] = 0;
			}
		}
		else
		{
			if (vexRT[Btn6U])
			{
				motor[LIFT] = 128;
			}
			else if (vexRT[Btn6D])
			{
				motor[LIFT] = -128;
			}
			else
			{
				motor[LIFT] = 0;
			}
		}

		if (kill)
		{
			if (kill_timer)
			{
				motor[LIFT] = -128;
			}
			else
			{
				motor[LIFT] = 128;
			}
		}

		if (!instantaneous)
		{
			applySoftStart();
		}

		wait1Msec(10);
	}
}
