#pragma config(Motor,  port2,           FR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port3,           FL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port4,           BR,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port5,           BL,            tmotorVex393HighSpeed_MC29, openLoop)
#pragma config(Motor,  port6,           ARM1,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port7,           ARM2,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port8,           ARM3,          tmotorVex393_MC29, openLoop)
#pragma config(Motor,  port9,           ARM4,          tmotorVex393_MC29, openLoop)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main() {
	while (true) {
		motor[FR] = -Ch1 + Ch2;
		motor[FL] = -Ch1 - Ch2;
		motor[BR] = -Ch1 + Ch2;
		motor[BL] = -Ch1 - Ch2;

		if (Btn6U) {
			motor[ARM1] = +40;
			motor[ARM2] = +40;
			motor[ARM3] = +40;
			motor[ARM4] = +40;
		}
		else if (Btn6D) {
			motor[ARM1] = -40;
			motor[ARM2] = -40;
			motor[ARM3] = -40;
			motor[ARM4] = -40;
		}
		else {
			motor[ARM1] = 0;
			motor[ARM2] = 0;
			motor[ARM3] = 0;
			motor[ARM4] = 0;
		}
	}
}
