#pragma config(I2C_Usage, I2C1, i2cSensors)
#pragma config(Sensor, I2C_1,  LEFT,           sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Sensor, I2C_2,  RIGHT,          sensorQuadEncoderOnI2CPort,    , AutoAssign )
#pragma config(Motor,  port2,           LEFT,          tmotorVex393TurboSpeed_MC29, openLoop, encoderPort, I2C_1)
#pragma config(Motor,  port3,           RIGHT,         tmotorVex393TurboSpeed_MC29, openLoop, reversed, encoderPort, I2C_2)
//*!!Code automatically generated by 'ROBOTC' configuration wizard               !!*//

task main()
{
	bool racing = false;
	bool _Btn8D = false;

	float delta_L = 0;

	while (true)
	{
		int data = nMotorEncoder[RIGHT];
		writeDebugStream("Encoder: %d\n", data);

		int forward_channel = vexRT[Ch3];
		int turn_channel = vexRT[Ch1];

		int effort_L = 0;
		int effort_R = 0;

		if (vexRT[Btn8D])
		{
			if (!_Btn8D)
			{
				racing = !racing;
				_Btn8D = true;
			}
		}
		else
		{
			_Btn8D = false;
		}



		if (racing)
		{
			int race_effort = 30;
			effort_L = race_effort;
			effort_R = race_effort;
		}
		else
		{
			effort_L = 0;
			effort_L = (forward_channel + turn_channel*0.5)/2;
			effort_R = (forward_channel - turn_channel*0.5)/2;
		}

		if (effort_L > 0)
		{
			int max_effort = getMotorVelocity(LEFT)*50.0/240.0 + 50;
			if (effort_L > max_effort)
			{
				effort_L = max_effort;
			}
		}

		if (effort_R > 0)
		{
			int max_effort = getMotorVelocity(RIGHT)*50.0/150.0 + 50;
			if (effort_R > max_effort)
			{
				effort_R = max_effort;
			}
		}

		/*
		float delta = getMotorVelocity(RIGHT) - getMotorVelocity(LEFT);
		float constant = 0.01;

		delta_L += constant*delta;

		float p = .1;

		effort_L = p*delta;
		*/

		motor[LEFT] = effort_L;
		motor[RIGHT] = effort_R;

		wait1Msec(10);
	}
}
